#!/bin/bash
# Monthly token efficiency research — runs 1st of each month at 06:00 PT
# Queries QMD for token efficiency patterns, appends findings to steward-findings.md

set -e

LOG="$HOME/helm-workspace/logs/monthly-research.log"
FINDINGS="$HOME/helm-workspace/system/steward-findings.md"
QMD="$HOME/marvin-bot/qmd-query.sh"
DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

mkdir -p "$(dirname "$LOG")" "$(dirname "$FINDINGS")"
echo "[$DATE] monthly-token-research starting" >> "$LOG"

# Query QMD for token efficiency patterns
if [ -f "$QMD" ]; then
    RESULT=$(bash "$QMD" "token efficiency patterns cache hit rate" 3 --min-relevance 0.7 2>/dev/null || echo "QMD query returned no results")
else
    RESULT="QMD not available at $QMD"
fi

# Append findings to steward-findings.md
cat >> "$FINDINGS" << FINDINGS_EOF

## Monthly Token Research — $(date -u +"%Y-%m-%d")
*Auto-generated by monthly-token-research.sh on the 1st of each month*

**QMD query:** "token efficiency patterns cache hit rate"
**Results:**
${RESULT:-No results above 0.7 relevance threshold}

---
FINDINGS_EOF

echo "[$DATE] Findings appended to steward-findings.md" >> "$LOG"

# Read daily-token-summary to surface any patterns worth queuing
SUMMARY="$HOME/helm-workspace/scripts/usage/daily-token-summary.json"
if [ -f "$SUMMARY" ]; then
    LOW_CACHE=$(python3 -c "
import json, sys
d=json.load(open('$SUMMARY'))
by_agent=d.get('by_agent_type',{})
low=[(k,v.get('cache_hit_rate_pct',100)) for k,v in by_agent.items() if v.get('cache_hit_rate_pct',100)<70]
for agent,rate in low: print(f'  {agent}: {rate:.1f}% cache hit')
" 2>/dev/null)
    if [ -n "$LOW_CACHE" ]; then
        echo "[$DATE] Low-cache agents detected (Level 1 investigation warranted):" >> "$LOG"
        echo "$LOW_CACHE" >> "$LOG"
        # Append to steward-findings for PM to review
        cat >> "$FINDINGS" << QUEUE_EOF
**Low cache-hit agents (action warranted):**
$LOW_CACHE
QUEUE_EOF
    fi
fi

echo "[$DATE] monthly-token-research complete" >> "$LOG"
